version: '3.8'
services:
  iptv-proxy:
    build: .
    container_name: iptv-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
      - XMLTV_URL=${XMLTV_URL}
      - PROVIDER_URL=${PROVIDER_URL}
      - JACKETT_HOST=${JACKETT_HOST}
      - JACKETT_API_KEY=${JACKETT_API_KEY}
      - PREFERRED_LANGUAGE=${PREFERRED_LANGUAGE}
